### ISSUE TITLE
patch_install success reported for patch_number: 0

### ISSUE THREAD

**Issue by felangel** [shorebirdtech/updater#89] opened 2023-09-21 20:41 UTC
I'm seeing a small number of patch_install success logs for patch_number 0 which should presumably never happen

```json
{
    "message": {
        "event": {
            "app_id": "<REDACTED>",
            "arch": "aarch64",
            "client_id": "<REDACTED>",
            "patch_number": 0,
            "platform": "android",
            "release_version": "<REDACTED>",
            "type": "__patch_install__"
        }
    }
}
```

**Comment by eseidel** [comment] 2023-09-21 20:58
For that to happen, report_launch_success would need to run:
https://github.com/shorebirdtech/updater/blob/bd86f617e1b94f8383ec293eb5f283f60f14e2af/library/src/updater.rs#L423
with a UpdaterState which is either new or loaded.
If it were new, current_boot_slot_index would be None, so I think it wouldn't do anything, so it needs to be loaded from disk (possibly racing with some other write?)

current_boot_patch would need to be Some.  current_boot_patch is only Some when current_boot_slot_index is Some:
https://github.com/shorebirdtech/updater/blob/bd86f617e1b94f8383ec293eb5f283f60f14e2af/library/src/cache.rs#L247

current_boot_slot_index is only set to Some inside activate_current_patch
https://github.com/shorebirdtech/updater/blob/bd86f617e1b94f8383ec293eb5f283f60f14e2af/library/src/cache.rs#L437
where it is copied (I think?) from next_boot_slot_index.

next_boot_slot_index is initialized to None and only set to Some in set_next_boot_patch_slot.
https://github.com/shorebirdtech/updater/blob/bd86f617e1b94f8383ec293eb5f283f60f14e2af/library/src/cache.rs#L449

next_boot_slot_index is only set in two places.
activate_latest_bootable_patch:
https://github.com/shorebirdtech/updater/blob/bd86f617e1b94f8383ec293eb5f283f60f14e2af/library/src/cache.rs#L327

and install_patch:
https://github.com/shorebirdtech/updater/blob/bd86f617e1b94f8383ec293eb5f283f60f14e2af/library/src/cache.rs#L411


Looking at activate_latest_bootable_patch.   activate_latest_bootable_patch calls:
latest_bootable_slot to get which slot to set:
https://github.com/shorebirdtech/updater/blob/bd86f617e1b94f8383ec293eb5f283f60f14e2af/library/src/cache.rs#L312C8-L312C28
That looks like it could end up setting an invalid slot, depending on what validate_slot does:
https://github.com/shorebirdtech/updater/blob/bd86f617e1b94f8383ec293eb5f283f60f14e2af/library/src/cache.rs#L286
Yeah, validate_slot could return a slot as if there is still a vmcode.dlc there, even if that slot has a invalid patch_number (0).  So that could happen if we lost our status.json but the cache was still there?  Maybe status.json had a race when writing it and was written invalid and then a later read caused it to reset, but leaving the cached patch there, which we then boot from successfully, report the success, except with patch zero?

Looking at install_patch:
Oh, the above might also happen when an install fails?

An install first clears a patch slot.  If that slot was in use (it shouldn't be?) it would end up clearing a patch slot and then saving status.json:
https://github.com/shorebirdtech/updater/blob/bd86f617e1b94f8383ec293eb5f283f60f14e2af/library/src/cache.rs#L387

clear_slot does try to delete our cache:
https://github.com/shorebirdtech/updater/blob/bd86f617e1b94f8383ec293eb5f283f60f14e2af/library/src/cache.rs#L348

I think the install otherwise looks ok.  So my current guess is this is happening from status.json getting lost.

**Comment by eseidel** [comment] 2023-09-21 21:00
Note I would expect this sort of loss-of-status.json could also cause potential crashes?  If we ever returned a invalid patch, we will also return a non-null path out the C API, but that path may not be valid (e.g. nothing should be at slot_0), we'd pass that invalid path to the dart runtime and then fail to launch, which could explain https://github.com/shorebirdtech/shorebird/issues/1226

**Comment by bryanoltman** [comment] 2023-09-26 17:16
Trying to reproduce this locally. So far have been unsuccessful. What hasn't worked so far:

1. Deleting `state.json` with a pending patch (`state.json` was regenerated, the patch installed successfully on the next run)
2. Writing junk data to `state.json`. Same as above.

**Comment by bryanoltman** [comment] 2023-09-26 17:57
Reproduced the issue by writing junk to the `slot_0/dlc.vmcode` and slot_1/dlc.vmcode` files with a patch installed. This also causes the app to repeatedly crash (i.e., we aren't handling the bad patch correctly)

**Comment by eseidel** [comment] 2023-09-26 18:22
I suspect that's a different crash than we're seeing in the wild though (also worth fixing!) since I believe Felix reported that each crash was for a unique device_id even though they all have patch_number=0 (e.g. uninitialized slot).

**Comment by bryanoltman** [comment] 2023-10-03 18:31
I believe this should be fixed by https://github.com/shorebirdtech/updater/pull/93

**Closed by bryanoltman** 2023-10-03 18:31 UTC
Labels: bug
